### ISSUE TITLE
Bug Report: Base64 Encoding Not Triggered on Re-Uploading Same Image

### ISSUE THREAD

**Issue by rtyaoke** [akinuri/image-to-base64#3]
# Bug Report
After selecting an image file, clicking the Reset button, and re-uploading the same image, it does not get base64 encoded.

I suspect this might be due to the use of the 'change' event in the following code.
https://github.com/akinuri/image-to-base64/blob/541a6b7d1e236215fffa760d3643350b7087ec85/index.html#L91C1-L110

# Bug Demo
https://github.com/akinuri/image-to-base64/assets/11521999/90172d6f-1ade-464f-8ffd-435cfdf45957

**Comment by rtyaoke** [comment]
Here is a reference article: 
https://zenn.dev/nana/articles/2b2cc0add0f5b5

(Apologies, the article is in Japanese)

**Comment by akinuri** [comment]
Hi. Thanks for taking an interest in this tool, and letting me know about this issue.

This is solved with the commit a402febb14656220ae797c0b588d65804d9654c4. The reset action should also clear the file input when it's triggered via the button. This was missing.

**Comment by rtyaoke** [comment]
I tried a few things manually from the Github page of this repository. It is working properly. 

Thank you for your smart code!
